model:
  diffusion:
    pretrained_model_name_or_path: 'runwayml/stable-diffusion-v1-5'
    train_unet: false
  lora:
    rank: 32
  noise_offset: 0
  prediction_type: null
  snr_gamma: 5.0

train:
  max_epoch: 1000
  dataset_path: 'csv路径'
  size: 512
  train_batch_size: 16
  num_workers: 4

  use_8bit_adam: false
  mixed_precision: fp16
  learning_rate: 1e-04
  max_grad_norm: 1

  warmup_method: linear
  warmup_iters: 100
  warmup_factor: 0.0001

  lr_scheduler: constant
  lr_warmup_steps: 0

  validation_prompt: '你的prompt'
  fid_real_image_root: '真实图片的根目录'
  max_to_keep: 30
  period: 10

  workspace: workspace/log

  gradient_accumulation_steps: 1
